#!/usr/bin/env bash
# =============================================================================
#  ITK-SNAP Memory Leak Test — macOS 'leaks' tool on existing Debug binary
#  No recompilation needed. Tests all targets (non-GUI and GUI).
#  Generated by Claude Code
# =============================================================================
set -o pipefail

REPORT="/Users/jileihao/dev/itksnap-dev/memory_leak_profiling/memory_leak_report.txt"
LOG_DIR="/Users/jileihao/dev/itksnap-dev/memory_leak_profiling/asan_logs"
DEBUG_DIR="/Users/jileihao/dev/itksnap-dev/memory_leak_profiling/build"
TEST_DATA="/Users/jileihao/dev/itksnap-dev/itksnap/Testing/TestData"

mkdir -p "$LOG_DIR"
mkdir -p "$DEBUG_DIR/Testing/Temporary"

exec > >(tee "$REPORT") 2>&1

echo "=================================================================="
echo "  ITK-SNAP Memory Leak Report (macOS 'leaks' tool)"
echo "  Date      : $(date)"
echo "  Host      : $(uname -n)"
echo "  OS        : $(sw_vers -productName) $(sw_vers -productVersion)"
echo "  Binary    : $DEBUG_DIR"
echo "  Report    : $REPORT"
echo "  Logs      : $LOG_DIR/"
echo "=================================================================="
echo ""
echo "Method: macOS 'leaks --atExit' with MallocStackLogging=1"
echo "Detects: heap memory leaks with allocation stack traces"
echo ""

PASS_COUNT=0
FAIL_COUNT=0
LEAK_COUNT=0

run_leaks_test() {
  local name="$1"; shift
  local cmd=("$@")
  local log="$LOG_DIR/${name}.leaks.log"

  echo "------------------------------------------------------------------"
  echo "TEST: $name"
  printf "CMD : %s\n" "${cmd[*]}"
  echo ""

  MallocStackLogging=1 \
  leaks --atExit -- "${cmd[@]}" > "$log" 2>&1
  local exit_code=$?

  # Show full leaks output
  if [ -s "$log" ]; then
    cat "$log"
  fi

  echo ""
  # 'leaks' exits 0=clean, 1=leaks found, other=error/crash
  if [ $exit_code -eq 0 ]; then
    echo "RESULT: PASS — no leaks detected"
    PASS_COUNT=$((PASS_COUNT + 1))
  elif [ $exit_code -eq 1 ] && grep -qE "leaks for process|LEAK" "$log" 2>/dev/null; then
    echo "RESULT: LEAKS DETECTED"
    LEAK_COUNT=$((LEAK_COUNT + 1))
  else
    echo "RESULT: FAIL (exit $exit_code — test error or crash)"
    FAIL_COUNT=$((FAIL_COUNT + 1))
  fi
  echo ""
}

# ---------------------------------------------------------------------------
# Non-GUI tests
# ---------------------------------------------------------------------------
echo "##"
echo "## Non-GUI Tests"
echo "##"
echo ""

run_leaks_test "IRISApplicationTest" \
  "$DEBUG_DIR/logic_api_test"

run_leaks_test "TDigestTest" \
  "$DEBUG_DIR/testTDigest" \
  "$TEST_DATA/tdigest_test.nii.gz" "0.98"

run_leaks_test "BasicSlicingTestX39" \
  "$DEBUG_DIR/SlicingPerformanceTest" \
  "$TEST_DATA/MRIcrop-seg.gipl.gz" \
  "$DEBUG_DIR/Testing/Temporary/X39.nii.gz" "X" "39" "irisRLE"

run_leaks_test "BasicSlicingTestY55" \
  "$DEBUG_DIR/SlicingPerformanceTest" \
  "$TEST_DATA/MRIcrop-seg.gipl.gz" \
  "$DEBUG_DIR/Testing/Temporary/Y55.nii.gz" "Y" "55" "irisRLE"

run_leaks_test "BasicSlicingTestZ32" \
  "$DEBUG_DIR/SlicingPerformanceTest" \
  "$TEST_DATA/MRIcrop-seg.gipl.gz" \
  "$DEBUG_DIR/Testing/Temporary/Z32.nii.gz" "Z" "32" "irisRLE"

# ---------------------------------------------------------------------------
# GUI tests
# ---------------------------------------------------------------------------
echo "##"
echo "## GUI Tests (ITK-SNAP --test)"
echo "##"
echo ""

ITKSNAP="$DEBUG_DIR/ITK-SNAP"

if [ ! -x "$ITKSNAP" ]; then
  echo "[WARN] ITK-SNAP binary not found at $ITKSNAP — skipping GUI tests."
else
  GUI_TESTS=(
    Workspace
    NaNs
    DiffSpace
    EchoCartesianDicomLoading
    LabelSmoothing
    PreferencesDialog
    ProbeIntensity
    RegionCompetition
    RandomForest
    RandomForestBailOut
    MeshImport
    MeshWorkspace
    SegmentationMesh
    VolumeRendering
    Reloading
  )

  for test_name in "${GUI_TESTS[@]}"; do
    run_leaks_test "$test_name" \
      "$ITKSNAP" "--test" "$test_name" \
      "--testacc" "1.0" "--testdir" "$TEST_DATA" "--lang" "en"
  done
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
TOTAL=$((PASS_COUNT + FAIL_COUNT + LEAK_COUNT))
echo "=================================================================="
echo "  SUMMARY"
echo "=================================================================="
echo "  Total tests  : $TOTAL"
echo "  Passed       : $PASS_COUNT"
echo "  Failed       : $FAIL_COUNT"
echo "  Leaks        : $LEAK_COUNT"
echo ""
echo "  Report  : $REPORT"
echo "  Logs    : $LOG_DIR/"
echo "  Finished: $(date)"
echo "=================================================================="
